#!/bin/zsh

typeset -gr CHROME_DEV_MCP_UXC_LINK_MARKER="# Generated by chrome-dev-mcp setup; do not edit by hand"
typeset -gr CHROME_DEV_MCP_UXC_IDLE_TTL="900"

chrome_dev_mcp_render_uxc_link() {
  local wrapper="$1" exclusive_key="$2" skill_dir="$3" link_dir="$4" mode="${5:-current}"
  local value
  for value in "$wrapper" "$exclusive_key" "$skill_dir" "$link_dir"; do
    [[ "$value" != *"'"* && "$value" != *$'\n'* ]] || return 69
  done
  print -r -- '#!/usr/bin/env sh'
  if [[ "$mode" == legacy ]]; then
    print -r -- '# Generated by uxc link; do not edit by hand'
    print -r -- "UXC_DAEMON_EXCLUSIVE='$exclusive_key' UXC_DAEMON_IDLE_TTL='$CHROME_DEV_MCP_UXC_IDLE_TTL' UXC_LINK_SKILL='chrome-dev-mcp' UXC_LINK_SKILL_PATH='$skill_dir' UXC_LINK_NAME='chrome-dev-mcp-cli' exec uxc '$wrapper' \"\$@\""
  else
    print -r -- "$CHROME_DEV_MCP_UXC_LINK_MARKER"
    print -r -- "cd '$skill_dir' || exit 69"
    print -r -- "UXC_DAEMON_EXCLUSIVE='$exclusive_key' UXC_DAEMON_IDLE_TTL='$CHROME_DEV_MCP_UXC_IDLE_TTL' UXC_LINK_SKILL='chrome-dev-mcp' UXC_LINK_SKILL_PATH='$skill_dir' UXC_LINK_NAME='chrome-dev-mcp-cli' exec '$link_dir/uxc' '$wrapper' \"\$@\""
  fi
}

chrome_dev_mcp_uxc_link_contract_matches() {
  local link_path="$1" wrapper="$2" exclusive_key="$3" skill_dir="$4" mode="${5:-current}"
  local expected
  [[ ! -L "$link_path" && -f "$link_path" && -x "$link_path" ]] || return 69
  expected="$(chrome_dev_mcp_render_uxc_link "$wrapper" "$exclusive_key" "$skill_dir" "${link_path:h}" "$mode")" || return 69
  [[ "$(<"$link_path")" == "$expected" ]]
}
