#!/bin/zsh

typeset -gr CHROME_DEV_MCP_UXC_LINK_MARKER="# Generated by uxc link; do not edit by hand"
typeset -gr CHROME_DEV_MCP_UXC_IDLE_TTL="900"

chrome_dev_mcp_uxc_link_contract_matches() {
  local link_path="$1"
  local wrapper="$2"
  local exclusive_key="$3"
  local skill_dir="$4"
  local expected_exec

  [[ "$wrapper" != *"'"* && "$wrapper" != *$'\n'* ]] || return 69
  [[ "$exclusive_key" != *"'"* && "$exclusive_key" != *$'\n'* ]] || return 69
  [[ "$skill_dir" != *"'"* && "$skill_dir" != *$'\n'* ]] || return 69

  expected_exec="UXC_DAEMON_EXCLUSIVE='$exclusive_key' UXC_DAEMON_IDLE_TTL='$CHROME_DEV_MCP_UXC_IDLE_TTL' UXC_LINK_SKILL='chrome-dev-mcp' UXC_LINK_SKILL_PATH='$skill_dir' UXC_LINK_NAME='chrome-dev-mcp-cli' exec uxc '$wrapper' \"\$@\""

  [[ ! -L "$link_path" && -f "$link_path" && -x "$link_path" ]] || return 69
  /usr/bin/grep -Fqx "$CHROME_DEV_MCP_UXC_LINK_MARKER" "$link_path" || return 69
  /usr/bin/grep -Fqx "$expected_exec" "$link_path" || return 69
}
