#!/bin/zsh

set -euo pipefail

script_dir="${0:A:h}"
source "$script_dir/lib/load-config.zsh"

wrapper=""
launcher=""
exclusive_key=""
link_dir=""
config_path="$(chrome_dev_mcp_config_path)"

fail_closed() {
  print -u2 -- "STATUS=ERROR"
  print -u2 -- "ERROR_CLASS=$1"
  exit 69
}

require_value() {
  [[ $# -ge 2 && -n "$2" && "$2" != --* ]] || fail_closed "missing_option_value"
}

while (( $# > 0 )); do
  case "$1" in
    --wrapper)
      require_value "$@"
      wrapper="$2"
      shift 2
      ;;
    --launcher)
      require_value "$@"
      launcher="$2"
      shift 2
      ;;
    --uxc-exclusive-key)
      require_value "$@"
      exclusive_key="$2"
      shift 2
      ;;
    --link-dir)
      require_value "$@"
      link_dir="$2"
      shift 2
      ;;
    --config)
      require_value "$@"
      config_path="$2"
      shift 2
      ;;
    *) fail_closed "unexpected_arguments" ;;
  esac
done

[[ -x "$wrapper" ]] || fail_closed "wrapper_missing"
[[ -x "$launcher" ]] || fail_closed "launcher_missing"
[[ -n "$exclusive_key" ]] || fail_closed "exclusive_key_missing"
[[ -n "$link_dir" ]] || fail_closed "link_dir_missing"

config_dir="${config_path:h}"
/bin/mkdir -p "$config_dir"
tmp_path="$(mktemp "$config_dir/config.zsh.XXXXXX")"
cleanup() {
  /bin/rm -f -- "$tmp_path"
}
trap cleanup EXIT INT TERM

{
  print -r -- "# Generated by chrome-dev-mcp; local-only runtime configuration."
  print -r -- "typeset -gx CHROME_DEV_MCP_WRAPPER=${(qqq)wrapper}"
  print -r -- "typeset -gx CHROME_DEV_MCP_LAUNCHER=${(qqq)launcher}"
  print -r -- "typeset -gx CHROME_DEV_MCP_UXC_EXCLUSIVE_KEY=${(qqq)exclusive_key}"
  print -r -- "typeset -gx CHROME_DEV_MCP_LINK_DIR=${(qqq)link_dir}"
} >| "$tmp_path"

/usr/bin/install -m 0600 "$tmp_path" "$config_path"
print -- "CHROME_DEV_MCP_CONFIG=READY"
print -- "CONFIG_PATH=$config_path"
