#!/bin/zsh

typeset -gr ARDOT_MCP_UXC_OWNER="ardot-mcp"
typeset -gr ARDOT_MCP_ENDPOINT="https://ardot.tencent.com/mcp"
typeset -gr ARDOT_MCP_LINK_NAME="ardot-mcp-cli"
typeset -gr ARDOT_MCP_CREDENTIAL_ID="ardot-mcp"
typeset -gr ARDOT_MCP_BINDING_ID="ardot-mcp"
typeset -gr ARDOT_MCP_OAUTH_SCOPE="mcp:use"
typeset -gr ARDOT_MCP_REDIRECT_URI="http://127.0.0.1:8788/callback"
typeset -gr ARDOT_MCP_UXC_LINK_MARKER="# Generated by ardot-mcp setup; do not edit by hand"

ardot_mcp_default_link_dir() {
  local data_home="${XDG_DATA_HOME:-${HOME}/.local/share}"
  print -r -- "$data_home/ardot-mcp"
}

ardot_mcp_resolve_link_dir() {
  if [[ -n "${ARDOT_MCP_LINK_DIR:-}" ]]; then
    print -r -- "$ARDOT_MCP_LINK_DIR"
    return
  fi
  ardot_mcp_default_link_dir
}
